# Generated by Django 3.2.21 on 2023-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='onBoardingRequired',
        ),
        migrations.AddField(
            model_name='user',
            name='onBoardingRequired',
            field=models.BooleanField(default=True),
        ),
    ]
